package com.xiaohua.novel.agent.domain;

public enum AgentRunState {
    CREATED,
    RESEARCHING,
    GENERATING_PROPOSALS,
    WAITING_CREATIVE_SELECTION,
    INITIALIZING_NOVEL,
    PLANNING_CHAPTERS,
    READY_TO_WRITE,
    GENERATING_CHAPTER,
    VALIDATING_OUTPUT,
    REVIEWING_QUALITY,
    CHECKING_CONTINUITY,
    REVISING_CHAPTER,
    COMMITTING_CHAPTER,
    WAITING_USER_DECISION,
    PAUSED,
    PAUSED_BY_BUDGET,
    COMPLETED,
    FAILED
}
